### ISSUE TITLE
how to deploy and load network workloads

### ISSUE THREAD

**Issue by mariobassem** [threefoldtecharchive/grid3_client_go#28]
the current solution in the terraform provider is to provide an object, containing both input from the user and records from the current local state, and work against this object, while manipulating it, trying to reach the desired final state the user provided, then save the final state locally...

the flow here is different: a user provides their desired state in one step, then loads the final state in another...

the problem with this is that the access node does not depend on the user input as it's chosen randomly, so it could be changed if the user made an update on the network workload...

so, does a user need to provide some context to the current state when deploying, or is there a work around???

i think if we could use the meta field in a workload, i don't really know what it is used for, to identify the access node, then we could load the current state successfully. (we could use it in k8s deployments as well)

**Comment by muhamadazmy** [comment]
I am not sure about implementation details of the terraform plugin. But for sure changing the access point for the user on network update is incorrect process (unless it's intended, asked by the user or whatever) but randomly choosing the access point every time the user does a network update is definitely wrong.

The point is, when you have an access point in your network that your wireguard config is built to use this to reach into your network. changing this means after each update the user has to create and restart wireguard to be able to reach the network.

Changing the access point then is acceptable if and only if it has to be done (access point is down, or user choose specifically to move)

So where do you store this state. Well, that's totally up to you! Terraform has a "project" directory where it keeps all what it needs to know about the setup. As a library you should provide the tool to load state from bytes (and generate bytes) and then it's up to the user of this library to save them (and load them) for your library to work.

It will be hard for me to give a design advice because seems that this library will eventually be used by terraform. and I don't know the internals of terrafrom tbh. But from the grid point of view i would suggest something like this.
- Your mean object is a `Project` or a `Network`. 
- You can add a list of all nodes to deploy on to this network, you can have 0 or more access points depends on how you wanna reach into your vms. if you have 0 access points, then your ownly way to reach VMs is either via public Ips (v4, or v6) or yggdrasil. The VMs can still talk to each other over wireguard.
- Add all related objects to the network (disks, qsfs, zdb, etc...)
- Choose which node hosts which VM, multiple VMs can deploy on the same node. 
- Same for ZDBs
- With all this data you will have one, or multiple Deployments objects (contract) 
- The entire project object should be persistable. You should be able to serialize and deserialize it. This represent the "target" state of the object
- Deployments are deployed
- Contracts IDs are stored (in the same project object) because these are needed to query the state
- Wait for all deployment to finish running. Now you can have the current state of the deployment. This can be optionally persisted because this state can be retrieved always from both the chain and nodes.
- The node provides an API to get you the "history" of a deployment (so you can see state change on VMs)
- Your library can (using the state and the target state) give lots of information like
  - What has been deployed
  - What has failed
  - What is running 
  - How your network is structured 
- How to add more nodes to your setup (simply update network workloads to know about new nodes)

IMHO this is what a good grid sdk should be able to do (from the top of my head). This this library can then used by tools to abstract the grid operations. for example used by terraform, or even with the app to visually build your setup by dragging and dropping object in a sophisticated UI

**Comment by muhamadazmy** [comment]
The workload data on the contract is very limited in size (512 bytes) so you can use it to store a very limited metadata if needed.

**Comment by mariobassem** [comment]
ok, so in terraform the first time the access point is randomly selected, the first valid one. Then in updates, it can be decided the node has to be changes or not since there is a local state to work against...
but currently the library does not persist state, and we depend on the user to provide it (hopefully only nodeIDs, contractIDs, and workload names) to successfully update and load deployments.

so, do we work on persisting state now, or depend on the user provided one??

**Comment by muhamadazmy** [comment]
The library doesn't have to persist state itself, it just need to be able to work with state. it's up to the user to provide this correct state. hence you gave the user the option to choose how to store his state. 

From what I see it there are 2 states that u want to always have:
- The target state (basically the Deployment as requested by the user)
- And the associated contract ids (if those already created)

Not sure if this answers your questions
